version: "3"

services:
   spring:
     restart: always
     build:
       context: ./back
       dockerfile: Dockerfile
     image: datecourse/back
     ports:
       - 8080:8080
     links:
       - db
     depends_on:
       - db


   nginx:
     restart: always
     build:
       context: ./nginx
       dockerfile: Dockerfile
     ports:
       - "3050:80"
