version: "3"

services:
   spring:
     build:
       context: ./back
       dockerfile: Dockerfile
     deploy:
       replicas: 3
     ports:
       - 8080
     depends_on:
      - redis
     links:
       - redis

   redis:
     image: redis
     ports:
       - 6379:6379

   nginx:
     image: nginx:alpine
     depends_on:
       - spring
     ports:
       - 80:80
     volumes:
       - ./nginx/default.conf:/etc/nginx/nginx.conf
