spring:
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
    #        secure: true https에서 만 동작할지 설정
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB

  resources:
    add-mappings: true


  datasource:
    hikari:
      master:
        jdbc-url: jdbc:mysql://localhost:3301/opencourse?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
        username: root
        password: test1
        driver-class-name: com.mysql.cj.jdbc.Driver
        data-source-properties:
          rewriteBatchedStatements: true
      slave:
        jdbc-url: jdbc:mysql://localhost:3302/opencourse?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
        username: root
        password: test2
        driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
          provider_disables_autocommit: true
        show_sql: true
        format_sql: true
        ddl-auto: create
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  redis:
    session:
      host: localhost
      port: 6379
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 268835850747-65ln6hknjlni444egh9tfqu2gabr3t4i.apps.googleusercontent.com
            client-secret: 8Km7wTWOgb1TZn_JUOe4elUW
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
logging:
  level:
    org.springframework.jdbc.datasource.SimpleDriverDataSource: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG
#  config: classpath:log4j2-dev.xml


cloud:
  aws:
    credentials:
      access-key: AKIA4IGL4EPNQNIL6AUJ
      secret-key: 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
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      image:
        bucket: datecourse
